name: Docker Build & Push
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - epgd-logo.svg
      - Jenkinsfile
  workflow_dispatch:
    inputs:
      tags:
        description: 'Scenario tags'
        type: choice
        options:
          - test
          - bld_all
          - bld_debian
          - bld_ubuntu
        required: true
      trigger:
        type: string
jobs:
  docker:
    if: ${{ github.event.inputs.tags != 'test' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push - DEBIAN
        if: ${{ (github.event.inputs.tags == 'bld_debian') || (github.event.inputs.tags == 'bld_all') }}
        uses: docker/build-push-action@v5
        with:
          build-args: |
            baseIMAGE=debian
            baseTAG=stable-slim
          no-cache: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}:${{ env.latestTAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}:debian
            ghcr.io/${{ github.repository }}:${{ env.latestTAG }}
            ghcr.io/${{ github.repository }}:debian
      - name: Build and push - UBUNTU
        if: ${{ (github.event.inputs.tags == 'bld_ubuntu') || (github.event.inputs.tags == 'bld_all') }}
        uses: docker/build-push-action@v5
        with:
          build-args: |
            baseIMAGE=ubuntu
            baseTAG=latest
          no-cache: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}:ubuntu
            ghcr.io/${{ github.repository }}:ubuntu
      - name: Send mail
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.GMAIL_USER}}
          password: ${{secrets.GMAIL_PASS}}
          from: GitHub
          to: ${{secrets.EMAIL}}
          subject: "Action ${{job.status}}: ${{github.repository}} - ${{github.workflow}} (${{github.event.inputs.tags}}) #${{github.run_id}}"
          body: |
            ${{job.status}}
            Action "${{github.workflow}} (${{github.event.inputs.tags}})" started by ${{github.actor}} (${{ github.event.inputs.trigger }}) in ${{github.repository}}.
            View workflow run: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
            Your faithful employee
            ${{runner.name}} (${{runner.os}} - ${{runner.arch}})
          html_body: |
            <!DOCTYPE html>
            <html>
            <body>
            <h1 style="text-transform:uppercase">${{job.status}}</h1>
            <p>Action "${{github.workflow}} (${{github.event.inputs.tags}})" started by ${{github.actor}} (${{ github.event.inputs.trigger }}) in ${{github.repository}}.</p>
            <p><a href="${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}" target="_blank" style="background-color:#4CAF50; border:none; color:white; padding:20px; text-align:center; text-decoration:none; display:inline-block; font-size:16px; margin:4px 2px; cursor:pointer; border-radius:12px;">View workflow run</a></p>
            <p>Your faithful employee<br>
            ${{runner.name}} (${{runner.os}} - ${{runner.arch}})</p>
            </body>
            </html>
          priority: low
    env:
      latestTAG: latest
      REPOSITORY: vdr-epg-daemon
